/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.abacus4.wakeup

import java.text.SimpleDateFormat
import java.util.*

class App {
    private val df = SimpleDateFormat("Gy年M月d日(E) H時m分s秒", Locale("ja", "JP", "JP"))
    var args:Array<String>? = null
    val greeting: String
    get() {
      return "Hello World! -- ${df.format(Date())}"
    }
}

fun main(args: Array<String>) {
  val app = App()
  println(app.greeting)
  app.args = args
  println("いつまでも愛しています…" + args.joinToString(", ", "[", "]"))
  println("Kotlin Version: ${KotlinVersion.CURRENT} Java Version: ${System.getProperty("java.version")}")
  val props = System.getProperties()
  for (e in props!!.keys.toList().stream().sorted()) {
    println("$e -> ${System.getProperty(e.toString())}")
  }
  println("JavaのList.forEach(voidを返すLambda式)")
  val keys = props!!.keys.map { e -> e.toString() }
  println(keys.sorted())
  val list = listOf(1,3,10,8,20,9)
  println(list.sorted())


}
