/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.abacus4.wakeup

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        val app = App()
        assertNotNull(app.greeting, "app should have a greeting")
    }
}
