/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.abacus4.wakeup

import java.text.SimpleDateFormat
import java.util.*

class App {
    private val df = SimpleDateFormat("Gy年M月d日(E) H時m分s秒", Locale("ja", "JP", "JP"))

    val greeting: String
    get() {
      return "Hello World! -- ${df.format(Date())}"
    }
}

fun main(args: Array<String>) {
  println(App().greeting)
  println("いつまでも愛しています…" + args.joinToString(", ", "[", "]"))
}
